version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongodb:27017/collaborative_editor
      JWT_SECRET: your_jwt_secret_key
      CLIENT_URL: http://localhost:3000
      PORT: 5000
      GEMINI_API_KEY: YOUR_GEMINI_API_KEY
    depends_on:
      - mongodb

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "3000:80"
    environment:
      REACT_APP_SERVER_URL: http://localhost:5000
    depends_on:
      - server

volumes:
  mongo_data:
